"""set unique constraint cart_id and product_id

Revision ID: 90820461f556
Revises: b4bc71742ec1
Create Date: 2021-07-17 18:40:13.203114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90820461f556'
down_revision = 'b4bc71742ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('cart_product_uc', 'carts_products', ['cart_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_product_uc', 'carts_products', type_='unique')
    # ### end Alembic commands ###
