"""set unique email on customer table

Revision ID: b4bc71742ec1
Revises: 0f3fc1cf69ee
Create Date: 2021-07-17 12:15:29.983522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4bc71742ec1'
down_revision = '0f3fc1cf69ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'customers', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='unique')
    # ### end Alembic commands ###
